apiVersion: apps/v1
kind: Deployment
metadata:
 name: httpd-deployment-prod
 namespace: lmk-prod
spec:
 selector:
   matchLabels:
    type: web
 replicas: 1
 template:
   metadata:
     labels:
       type: web
   spec:
    containers:
    - name: container
      image: nuy0307/second_front:latest
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m